language:
    - objective-c

env:
    global:
        # Encrypted token for uploading conda packages to Anaconda.org
        # First create a token using:
        # anaconda auth --create --name CommandCI --scopes 'repos conda'
        # Then encrypt:
        # travis encrypt TOKEN=xx-tokenfrom-above
        # This must be done from the CommandCI/CommandCI_conda repository
        - secure: "KJmyVmJvUy1Fnyzk09f/q69gLmo+y/PqcyrQv+wZFBQvC4ZVLhNMZxE8VNxa96MjQHD3x3cTll5qBC6JVIL2+d3YJ/0p3MfUnZbsu/KFqLlV3LFNqohXrlJSGQYluidSz4WgfAoRrFNxoTgZ9bYrVwhMwo/2mbXz5EyeZITWSoOtRCZJi+6wjVP9Bb5kCEQaRqI3w3+DG2QYwqKKAjUERHpFftKeHOZS+7jLX6Krh6uQumR9yirmiSPbs5mChOxyXQyS+aQmc3oFKrMzPfB+fo0lc8mL5VLVEH5WFtQlyXDWxJvgFRbjFjqlpesHjudg+XBjPREs6Wsu4Q3nECZs2FeMRjO9Y7pg4dtGbxNedFfm6o5kKTClrRZ+geJAsd4ynv95Xu62TM6clS0jbVrl/D6BSAYr3PPUr6aGoMNUgqMhqjs52HtQDPbqqIbbNAJ6jImMclgU/pH63E1/4fa8UCcM1IKALX1j1vViGb3T3/bEfR2C1khVIz7FC1Csh400N46xzBqzxTof046rh3rFuXyk7ur9K82uLcgWI6lKEQPK5k6+9QLRIiLirkHFYW2Bu79ajGjPTpkyoUEAUEtv9DeRh9B0jEM069g9TSKgDfjhx2/TvX4ecMW7flTMcXtYakakeDwumANs3wwkjOtyxGtw8XfWhGi4766AeUUSRcU="

install: 
    - MINICONDA_URL="https://repo.continuum.io/miniconda"
    - MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    - wget "${MINICONDA_URL}/${MINICONDA_FILE}"
    - bash $MINICONDA_FILE -b
    - export PATH=/Users/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda install --yes conda-build jinja2 anaconda-client
    - mkdir ~/conda-bld
    - export CONDA_BLD_PATH=~/conda-bld

script:
    - | 
      if [ ! -f build_script_osx-64.sh ]; then
        echo "Creating build script from YAML file"
        python create_build_script.py build_specs.yml osx-64 > build_script_osx-64.sh
        chmod +x build_script_osx-64.sh
      fi
    - ./build_script_osx-64.sh

after_success:
    # List files created
    - cd ~/conda-bld
    - ls */*.tar.bz2
    # Upload to Anaconda.org
    - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
          ls */*.tar.bz2 >/dev/null 2>&1 && anaconda -t $TOKEN upload */*.tar.bz2;
      fi
