language:
    - objective-c

env:
    global:
        # Encrypted token for uploading conda packages to Anaconda.org
        # First create a token using:
        # anaconda auth --create -o CommandCU --name CommandCI --scopes 'repos conda'
        # Then encrypt:
        # travis encrypt TOKEN=xx-tokenfrom-above
        # This must be done from the CommandCI/CommandCI_conda repository
        secure: "GSG18XVsHdPP53A1HxCAQUg3uf/M5hpbi2Em3hCQSQO7ZI8myHuMj7kGuKfA6M4dpu0jYrCcA5glTbOR3yLRB1feuh2fIX6g1sUa839r+Q7UDLeSY7dag5IT/CAHYAttRoarpb6bafsC73hIYOjU1VPP5aVxY5Nak3BQkSMBlGFi8b0tM1QeAzxdir2ZH2Pb3/t0d8iXNTR38aamRCfMzk8QatpAt5CmxcWAjXfkXxUgNqjJJZm5zMHGCjnlWTYzNeeMvtlAglOTI9zrmGjADL/SKnoYhFyLNRhm6tj49/E5cbNiM/uzPCMABKGHTvD2K7Ev/cTIxG0IH6wL1I6tofR/M4KpMJTr2Q8H1ufSmpB48XfDb70i9edLdtEvPhsXQWp6gB2/osStHWbprGdvsoWepBpwslIEg3KkvJhF8pqSigAof6iYSynwa3KjjnCuHvfiUHrIWMaj9gSrM2pUhthSU7Wv7o9U9Nu4P1JwmRaA9SM4LCmwXNq4B7BVsHxzK7MfLD3P6IDaR5MpjIy+2wVZdcpzwsW5Or8NDgywLRZp6mhnmUCUv+xciX8Y1PayBzpdAgINjmJ5fbENGeZmiglvw8jIvda4Qxe8SjK5aJSkJJocSvAmkT7EcW4ldSR9weo6GeF7JUb2bnfZN9k9eDU3vUMgckzLjxjwb8K8N7g="

install: 
    - MINICONDA_URL="https://repo.continuum.io/miniconda"
    - MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    - wget "${MINICONDA_URL}/${MINICONDA_FILE}"
    - bash $MINICONDA_FILE -b
    - export PATH=/Users/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda install --yes conda-build jinja2 anaconda-client
    - mkdir ~/conda-bld
    - export CONDA_BLD_PATH=~/conda-bld

script:
    - | 
      if [ ! -f build_script_osx-64.sh ]; then
        echo "Creating build script from YAML file"
        python create_build_script.py build_specs.yml osx-64 > build_script_osx-64.sh
        chmod +x build_script_osx-64.sh
      fi
    - ./build_script_osx-64.sh

after_success:
    # List files created
    - cd ~/conda-bld
    - ls */*.tar.bz2
    # Upload to Anaconda.org
    - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
          ls */*.tar.bz2 >/dev/null 2>&1 && anaconda -t $TOKEN upload */*.tar.bz2;
      fi
